org: rasec23rj
app: envs
service: envs
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, "qa"}
  environment: ${file(./config/env.${self:provider.stage}.json)}
  iamRoleStatements: ${file(./config/serveless/db.iam.role.yaml)}

custom:
  schedulerRate: rate(1 minute)
  enable: true
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

resources:
  Resources: ${file(./config/serveless/resources/dynamodb.hero.table.yaml)}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: commit messages each minute
          enabled: ${self:custom.enable}
